# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import controller_pb2 as controller__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in controller_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LocalControllerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTelemetry = channel.unary_unary(
                '/localcontroller.LocalController/StartTelemetry',
                request_serializer=controller__pb2.StartTelemetryRequest.SerializeToString,
                response_deserializer=controller__pb2.StartResponse.FromString,
                _registered_method=True)
        self.StartCallback = channel.unary_unary(
                '/localcontroller.LocalController/StartCallback',
                request_serializer=controller__pb2.StartCallbackRequest.SerializeToString,
                response_deserializer=controller__pb2.StartResponse.FromString,
                _registered_method=True)
        self.Configure = channel.unary_unary(
                '/localcontroller.LocalController/Configure',
                request_serializer=controller__pb2.ConfigureRequest.SerializeToString,
                response_deserializer=controller__pb2.ConfigureResponse.FromString,
                _registered_method=True)


class LocalControllerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartCallback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Configure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LocalControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTelemetry': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTelemetry,
                    request_deserializer=controller__pb2.StartTelemetryRequest.FromString,
                    response_serializer=controller__pb2.StartResponse.SerializeToString,
            ),
            'StartCallback': grpc.unary_unary_rpc_method_handler(
                    servicer.StartCallback,
                    request_deserializer=controller__pb2.StartCallbackRequest.FromString,
                    response_serializer=controller__pb2.StartResponse.SerializeToString,
            ),
            'Configure': grpc.unary_unary_rpc_method_handler(
                    servicer.Configure,
                    request_deserializer=controller__pb2.ConfigureRequest.FromString,
                    response_serializer=controller__pb2.ConfigureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'localcontroller.LocalController', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('localcontroller.LocalController', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LocalController(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/localcontroller.LocalController/StartTelemetry',
            controller__pb2.StartTelemetryRequest.SerializeToString,
            controller__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartCallback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/localcontroller.LocalController/StartCallback',
            controller__pb2.StartCallbackRequest.SerializeToString,
            controller__pb2.StartResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Configure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/localcontroller.LocalController/Configure',
            controller__pb2.ConfigureRequest.SerializeToString,
            controller__pb2.ConfigureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
