# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\x0flocalcontroller\"A\n\x15StartTelemetryRequest\x12\x19\n\x11kafka_broker_addr\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\"+\n\x14StartCallbackRequest\x12\x13\n\x0bserver_addr\x18\x01 \x01(\t\"\x1f\n\x10\x43onfigureRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"0\n\rStartResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x11\x43onfigureResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x97\x02\n\x0fLocalController\x12X\n\x0eStartTelemetry\x12&.localcontroller.StartTelemetryRequest\x1a\x1e.localcontroller.StartResponse\x12V\n\rStartCallback\x12%.localcontroller.StartCallbackRequest\x1a\x1e.localcontroller.StartResponse\x12R\n\tConfigure\x12!.localcontroller.ConfigureRequest\x1a\".localcontroller.ConfigureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTTELEMETRYREQUEST']._serialized_start=37
  _globals['_STARTTELEMETRYREQUEST']._serialized_end=102
  _globals['_STARTCALLBACKREQUEST']._serialized_start=104
  _globals['_STARTCALLBACKREQUEST']._serialized_end=147
  _globals['_CONFIGUREREQUEST']._serialized_start=149
  _globals['_CONFIGUREREQUEST']._serialized_end=180
  _globals['_STARTRESPONSE']._serialized_start=182
  _globals['_STARTRESPONSE']._serialized_end=230
  _globals['_CONFIGURERESPONSE']._serialized_start=232
  _globals['_CONFIGURERESPONSE']._serialized_end=267
  _globals['_LOCALCONTROLLER']._serialized_start=270
  _globals['_LOCALCONTROLLER']._serialized_end=549
# @@protoc_insertion_point(module_scope)
