apiVersion: consensus.atomix.io/v1beta1
kind: ConsensusStore
metadata:
  name: consensus-store
spec:
  replicas: 3
  groups: 3
  securityContext:
    fsGroup: 2000
    runAsUser: 1000
    runAsGroup: 1000
  volumeClaimTemplate:
    spec:
      accessModes:
        - ReadWriteOnce
      volumeMode: Filesystem
      resources:
        requests:
          storage: 8Gi
      storageClassName: do-block-storage