apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-service
  template:
    metadata:
      labels:
        app: telemetry-service
        proxy.atomix.io/inject: "true"
        proxy.atomix.io/profile: "ixp-storage-profile"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z ixp-kafka-kafka-bootstrap 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: telemetry-service
        image: telemetry-service:local
        env:
          - name: SCENARIO_PATH
            value: /etc/scenario/scenario.yaml
          - name: OTEL_SERVICE_NAME
            value: telemetry-service
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
          - name: TELEMETRY_MODE
            value: "collector"
        volumeMounts:
          - name: scenario-volume
            mountPath: /etc/scenario
            readOnly: true
          - name: kafka-tls
            mountPath: /etc/kafka-tls
            readOnly: true
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: "2"
            memory: 2Gi
      volumes:
        - name: scenario-volume
          configMap:
            name: test-scenario
        - name: kafka-tls
          secret:
            secretName: kafka-tls
            optional: true