apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-producer
  template:
    metadata:
      labels:
        app: dummy-producer
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox
        command: ['sh', '-c', 'until nc -z ixp-kafka-kafka-bootstrap 9092; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: dummy-producer
        image: dummy-producer:local
        env:
        - name: SCENARIO_PATH
          value: /etc/scenario/scenario.yaml
        - name: OTEL_SERVICE_NAME
          value: dummy-producer
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "otel-collector-opentelemetry-collector.observability.svc.cluster.local:4317"
        - name: TELEMETRY_MODE
          value: "collector"
        volumeMounts:
          - name: scenario-volume
            mountPath: /etc/scenario
            readOnly: true
          - name: kafka-tls
            mountPath: /etc/kafka-tls
            readOnly: true

      volumes:
        - name: scenario-volume
          configMap:
            name: test-scenario
        - name: kafka-tls
          secret:
            secretName: kafka-tls
            optional: true
---

apiVersion: v1
kind: Service
metadata:
  name: dummy-producer
spec:
  selector:
    app: dummy-producer
  ports:
    - port: 5005
      targetPort: 5005
      name: metrics
