// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: proto/virtual_circuit.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ASideId       uint64                 `protobuf:"varint,1,opt,name=a_side_id,json=aSideId,proto3" json:"a_side_id,omitempty"`
	BSideId       uint64                 `protobuf:"varint,2,opt,name=b_side_id,json=bSideId,proto3" json:"b_side_id,omitempty"`
	BandwidthKbps uint64                 `protobuf:"varint,3,opt,name=bandwidth_kbps,json=bandwidthKbps,proto3" json:"bandwidth_kbps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpRequest) Reset() {
	*x = SetUpRequest{}
	mi := &file_proto_virtual_circuit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpRequest) ProtoMessage() {}

func (x *SetUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtual_circuit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpRequest.ProtoReflect.Descriptor instead.
func (*SetUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtual_circuit_proto_rawDescGZIP(), []int{0}
}

func (x *SetUpRequest) GetASideId() uint64 {
	if x != nil {
		return x.ASideId
	}
	return 0
}

func (x *SetUpRequest) GetBSideId() uint64 {
	if x != nil {
		return x.BSideId
	}
	return 0
}

func (x *SetUpRequest) GetBandwidthKbps() uint64 {
	if x != nil {
		return x.BandwidthKbps
	}
	return 0
}

type SetUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUpResponse) Reset() {
	*x = SetUpResponse{}
	mi := &file_proto_virtual_circuit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUpResponse) ProtoMessage() {}

func (x *SetUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtual_circuit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUpResponse.ProtoReflect.Descriptor instead.
func (*SetUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtual_circuit_proto_rawDescGZIP(), []int{1}
}

func (x *SetUpResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

type TearDownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ASideId       uint64                 `protobuf:"varint,1,opt,name=a_side_id,json=aSideId,proto3" json:"a_side_id,omitempty"`
	BSideId       uint64                 `protobuf:"varint,2,opt,name=b_side_id,json=bSideId,proto3" json:"b_side_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TearDownRequest) Reset() {
	*x = TearDownRequest{}
	mi := &file_proto_virtual_circuit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TearDownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TearDownRequest) ProtoMessage() {}

func (x *TearDownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtual_circuit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TearDownRequest.ProtoReflect.Descriptor instead.
func (*TearDownRequest) Descriptor() ([]byte, []int) {
	return file_proto_virtual_circuit_proto_rawDescGZIP(), []int{2}
}

func (x *TearDownRequest) GetASideId() uint64 {
	if x != nil {
		return x.ASideId
	}
	return 0
}

func (x *TearDownRequest) GetBSideId() uint64 {
	if x != nil {
		return x.BSideId
	}
	return 0
}

type TearDownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSuccess     bool                   `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TearDownResponse) Reset() {
	*x = TearDownResponse{}
	mi := &file_proto_virtual_circuit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TearDownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TearDownResponse) ProtoMessage() {}

func (x *TearDownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_virtual_circuit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TearDownResponse.ProtoReflect.Descriptor instead.
func (*TearDownResponse) Descriptor() ([]byte, []int) {
	return file_proto_virtual_circuit_proto_rawDescGZIP(), []int{3}
}

func (x *TearDownResponse) GetIsSuccess() bool {
	if x != nil {
		return x.IsSuccess
	}
	return false
}

var File_proto_virtual_circuit_proto protoreflect.FileDescriptor

const file_proto_virtual_circuit_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/virtual_circuit.proto\x12\x12virtual_circuit.v1\"m\n" +
	"\fSetUpRequest\x12\x1a\n" +
	"\ta_side_id\x18\x01 \x01(\x04R\aaSideId\x12\x1a\n" +
	"\tb_side_id\x18\x02 \x01(\x04R\abSideId\x12%\n" +
	"\x0ebandwidth_kbps\x18\x03 \x01(\x04R\rbandwidthKbps\".\n" +
	"\rSetUpResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess\"I\n" +
	"\x0fTearDownRequest\x12\x1a\n" +
	"\ta_side_id\x18\x01 \x01(\x04R\aaSideId\x12\x1a\n" +
	"\tb_side_id\x18\x02 \x01(\x04R\abSideId\"1\n" +
	"\x10TearDownResponse\x12\x1d\n" +
	"\n" +
	"is_success\x18\x01 \x01(\bR\tisSuccess2\xb5\x01\n" +
	"\x0eVirtualCircuit\x12L\n" +
	"\x05SetUp\x12 .virtual_circuit.v1.SetUpRequest\x1a!.virtual_circuit.v1.SetUpResponse\x12U\n" +
	"\bTearDown\x12#.virtual_circuit.v1.TearDownRequest\x1a$.virtual_circuit.v1.TearDownResponseB!Z\x1fgithub.com/chew01/ixp-gcp/protob\x06proto3"

var (
	file_proto_virtual_circuit_proto_rawDescOnce sync.Once
	file_proto_virtual_circuit_proto_rawDescData []byte
)

func file_proto_virtual_circuit_proto_rawDescGZIP() []byte {
	file_proto_virtual_circuit_proto_rawDescOnce.Do(func() {
		file_proto_virtual_circuit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_virtual_circuit_proto_rawDesc), len(file_proto_virtual_circuit_proto_rawDesc)))
	})
	return file_proto_virtual_circuit_proto_rawDescData
}

var file_proto_virtual_circuit_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_virtual_circuit_proto_goTypes = []any{
	(*SetUpRequest)(nil),     // 0: virtual_circuit.v1.SetUpRequest
	(*SetUpResponse)(nil),    // 1: virtual_circuit.v1.SetUpResponse
	(*TearDownRequest)(nil),  // 2: virtual_circuit.v1.TearDownRequest
	(*TearDownResponse)(nil), // 3: virtual_circuit.v1.TearDownResponse
}
var file_proto_virtual_circuit_proto_depIdxs = []int32{
	0, // 0: virtual_circuit.v1.VirtualCircuit.SetUp:input_type -> virtual_circuit.v1.SetUpRequest
	2, // 1: virtual_circuit.v1.VirtualCircuit.TearDown:input_type -> virtual_circuit.v1.TearDownRequest
	1, // 2: virtual_circuit.v1.VirtualCircuit.SetUp:output_type -> virtual_circuit.v1.SetUpResponse
	3, // 3: virtual_circuit.v1.VirtualCircuit.TearDown:output_type -> virtual_circuit.v1.TearDownResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_virtual_circuit_proto_init() }
func file_proto_virtual_circuit_proto_init() {
	if File_proto_virtual_circuit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_virtual_circuit_proto_rawDesc), len(file_proto_virtual_circuit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_virtual_circuit_proto_goTypes,
		DependencyIndexes: file_proto_virtual_circuit_proto_depIdxs,
		MessageInfos:      file_proto_virtual_circuit_proto_msgTypes,
	}.Build()
	File_proto_virtual_circuit_proto = out.File
	file_proto_virtual_circuit_proto_goTypes = nil
	file_proto_virtual_circuit_proto_depIdxs = nil
}
