// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/virtual_circuit.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VirtualCircuit_SetUp_FullMethodName    = "/virtual_circuit.v1.VirtualCircuit/SetUp"
	VirtualCircuit_TearDown_FullMethodName = "/virtual_circuit.v1.VirtualCircuit/TearDown"
)

// VirtualCircuitClient is the client API for VirtualCircuit service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VirtualCircuitClient interface {
	SetUp(ctx context.Context, in *SetUpRequest, opts ...grpc.CallOption) (*SetUpResponse, error)
	TearDown(ctx context.Context, in *TearDownRequest, opts ...grpc.CallOption) (*TearDownResponse, error)
}

type virtualCircuitClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtualCircuitClient(cc grpc.ClientConnInterface) VirtualCircuitClient {
	return &virtualCircuitClient{cc}
}

func (c *virtualCircuitClient) SetUp(ctx context.Context, in *SetUpRequest, opts ...grpc.CallOption) (*SetUpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetUpResponse)
	err := c.cc.Invoke(ctx, VirtualCircuit_SetUp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtualCircuitClient) TearDown(ctx context.Context, in *TearDownRequest, opts ...grpc.CallOption) (*TearDownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TearDownResponse)
	err := c.cc.Invoke(ctx, VirtualCircuit_TearDown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtualCircuitServer is the server API for VirtualCircuit service.
// All implementations must embed UnimplementedVirtualCircuitServer
// for forward compatibility.
type VirtualCircuitServer interface {
	SetUp(context.Context, *SetUpRequest) (*SetUpResponse, error)
	TearDown(context.Context, *TearDownRequest) (*TearDownResponse, error)
	mustEmbedUnimplementedVirtualCircuitServer()
}

// UnimplementedVirtualCircuitServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVirtualCircuitServer struct{}

func (UnimplementedVirtualCircuitServer) SetUp(context.Context, *SetUpRequest) (*SetUpResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetUp not implemented")
}
func (UnimplementedVirtualCircuitServer) TearDown(context.Context, *TearDownRequest) (*TearDownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TearDown not implemented")
}
func (UnimplementedVirtualCircuitServer) mustEmbedUnimplementedVirtualCircuitServer() {}
func (UnimplementedVirtualCircuitServer) testEmbeddedByValue()                        {}

// UnsafeVirtualCircuitServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VirtualCircuitServer will
// result in compilation errors.
type UnsafeVirtualCircuitServer interface {
	mustEmbedUnimplementedVirtualCircuitServer()
}

func RegisterVirtualCircuitServer(s grpc.ServiceRegistrar, srv VirtualCircuitServer) {
	// If the following call panics, it indicates UnimplementedVirtualCircuitServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VirtualCircuit_ServiceDesc, srv)
}

func _VirtualCircuit_SetUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCircuitServer).SetUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCircuit_SetUp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCircuitServer).SetUp(ctx, req.(*SetUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtualCircuit_TearDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TearDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtualCircuitServer).TearDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VirtualCircuit_TearDown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtualCircuitServer).TearDown(ctx, req.(*TearDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VirtualCircuit_ServiceDesc is the grpc.ServiceDesc for VirtualCircuit service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VirtualCircuit_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "virtual_circuit.v1.VirtualCircuit",
	HandlerType: (*VirtualCircuitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUp",
			Handler:    _VirtualCircuit_SetUp_Handler,
		},
		{
			MethodName: "TearDown",
			Handler:    _VirtualCircuit_TearDown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/virtual_circuit.proto",
}
