// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: flow.proto

package virtualcircuitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Flow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IngressPort   *uint32                `protobuf:"varint,1,opt,name=ingress_port,json=ingressPort,proto3,oneof" json:"ingress_port,omitempty"`
	SourceVlanid  *uint32                `protobuf:"varint,2,opt,name=source_vlanid,json=sourceVlanid,proto3,oneof" json:"source_vlanid,omitempty"`
	EgressPort    *uint32                `protobuf:"varint,3,opt,name=egress_port,json=egressPort,proto3,oneof" json:"egress_port,omitempty"`
	DestVlanid    *uint32                `protobuf:"varint,4,opt,name=dest_vlanid,json=destVlanid,proto3,oneof" json:"dest_vlanid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_flow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_flow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_flow_proto_rawDescGZIP(), []int{0}
}

func (x *Flow) GetIngressPort() uint32 {
	if x != nil && x.IngressPort != nil {
		return *x.IngressPort
	}
	return 0
}

func (x *Flow) GetSourceVlanid() uint32 {
	if x != nil && x.SourceVlanid != nil {
		return *x.SourceVlanid
	}
	return 0
}

func (x *Flow) GetEgressPort() uint32 {
	if x != nil && x.EgressPort != nil {
		return *x.EgressPort
	}
	return 0
}

func (x *Flow) GetDestVlanid() uint32 {
	if x != nil && x.DestVlanid != nil {
		return *x.DestVlanid
	}
	return 0
}

var File_flow_proto protoreflect.FileDescriptor

const file_flow_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"flow.proto\x12\x12virtual_circuit.v1\"\xe7\x01\n" +
	"\x04Flow\x12&\n" +
	"\fingress_port\x18\x01 \x01(\rH\x00R\vingressPort\x88\x01\x01\x12(\n" +
	"\rsource_vlanid\x18\x02 \x01(\rH\x01R\fsourceVlanid\x88\x01\x01\x12$\n" +
	"\vegress_port\x18\x03 \x01(\rH\x02R\n" +
	"egressPort\x88\x01\x01\x12$\n" +
	"\vdest_vlanid\x18\x04 \x01(\rH\x03R\n" +
	"destVlanid\x88\x01\x01B\x0f\n" +
	"\r_ingress_portB\x10\n" +
	"\x0e_source_vlanidB\x0e\n" +
	"\f_egress_portB\x0e\n" +
	"\f_dest_vlanidB<Z:github.com/chew01/ixp-gcp/shared/proto/pb;virtualcircuitv1b\x06proto3"

var (
	file_flow_proto_rawDescOnce sync.Once
	file_flow_proto_rawDescData []byte
)

func file_flow_proto_rawDescGZIP() []byte {
	file_flow_proto_rawDescOnce.Do(func() {
		file_flow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)))
	})
	return file_flow_proto_rawDescData
}

var file_flow_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_flow_proto_goTypes = []any{
	(*Flow)(nil), // 0: virtual_circuit.v1.Flow
}
var file_flow_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_flow_proto_init() }
func file_flow_proto_init() {
	if File_flow_proto != nil {
		return
	}
	file_flow_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flow_proto_rawDesc), len(file_flow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flow_proto_goTypes,
		DependencyIndexes: file_flow_proto_depIdxs,
		MessageInfos:      file_flow_proto_msgTypes,
	}.Build()
	File_flow_proto = out.File
	file_flow_proto_goTypes = nil
	file_flow_proto_depIdxs = nil
}
