// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: telemetry_report.proto

package virtualcircuitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelemetryReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FlowId        *Flow                  `protobuf:"bytes,1,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"`
	RxByteCount   uint64                 `protobuf:"varint,2,opt,name=rx_byte_count,json=rxByteCount,proto3" json:"rx_byte_count,omitempty"`
	TxByteCount   uint64                 `protobuf:"varint,3,opt,name=tx_byte_count,json=txByteCount,proto3" json:"tx_byte_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelemetryReport) Reset() {
	*x = TelemetryReport{}
	mi := &file_telemetry_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelemetryReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelemetryReport) ProtoMessage() {}

func (x *TelemetryReport) ProtoReflect() protoreflect.Message {
	mi := &file_telemetry_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelemetryReport.ProtoReflect.Descriptor instead.
func (*TelemetryReport) Descriptor() ([]byte, []int) {
	return file_telemetry_report_proto_rawDescGZIP(), []int{0}
}

func (x *TelemetryReport) GetFlowId() *Flow {
	if x != nil {
		return x.FlowId
	}
	return nil
}

func (x *TelemetryReport) GetRxByteCount() uint64 {
	if x != nil {
		return x.RxByteCount
	}
	return 0
}

func (x *TelemetryReport) GetTxByteCount() uint64 {
	if x != nil {
		return x.TxByteCount
	}
	return 0
}

var File_telemetry_report_proto protoreflect.FileDescriptor

const file_telemetry_report_proto_rawDesc = "" +
	"\n" +
	"\x16telemetry_report.proto\x12\x12virtual_circuit.v1\x1a\n" +
	"flow.proto\"\x8c\x01\n" +
	"\x0fTelemetryReport\x121\n" +
	"\aflow_id\x18\x01 \x01(\v2\x18.virtual_circuit.v1.FlowR\x06flowId\x12\"\n" +
	"\rrx_byte_count\x18\x02 \x01(\x04R\vrxByteCount\x12\"\n" +
	"\rtx_byte_count\x18\x03 \x01(\x04R\vtxByteCountB<Z:github.com/chew01/ixp-gcp/shared/proto/pb;virtualcircuitv1b\x06proto3"

var (
	file_telemetry_report_proto_rawDescOnce sync.Once
	file_telemetry_report_proto_rawDescData []byte
)

func file_telemetry_report_proto_rawDescGZIP() []byte {
	file_telemetry_report_proto_rawDescOnce.Do(func() {
		file_telemetry_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_telemetry_report_proto_rawDesc), len(file_telemetry_report_proto_rawDesc)))
	})
	return file_telemetry_report_proto_rawDescData
}

var file_telemetry_report_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_telemetry_report_proto_goTypes = []any{
	(*TelemetryReport)(nil), // 0: virtual_circuit.v1.TelemetryReport
	(*Flow)(nil),            // 1: virtual_circuit.v1.Flow
}
var file_telemetry_report_proto_depIdxs = []int32{
	1, // 0: virtual_circuit.v1.TelemetryReport.flow_id:type_name -> virtual_circuit.v1.Flow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_telemetry_report_proto_init() }
func file_telemetry_report_proto_init() {
	if File_telemetry_report_proto != nil {
		return
	}
	file_flow_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_telemetry_report_proto_rawDesc), len(file_telemetry_report_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_telemetry_report_proto_goTypes,
		DependencyIndexes: file_telemetry_report_proto_depIdxs,
		MessageInfos:      file_telemetry_report_proto_msgTypes,
	}.Build()
	File_telemetry_report_proto = out.File
	file_telemetry_report_proto_goTypes = nil
	file_telemetry_report_proto_depIdxs = nil
}
